workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      
.curl_template: &curl_template |
 curl -X PUT --header "PRIVATE-TOKEN: $API_TOKEN" "https://vs.ekenya.co.ke:1126/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/merge"

stages:        
  - build
  - test
  - deploy
  - merge

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:   
  stage: test 
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - echo "Code coverage is 90%"

lint-test-job:   
  stage: test  
  script:
    - echo "Linting code... This will take about 10 seconds."
    - echo "No lint issues found."

deploy-job:      
  stage: deploy  
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

mergeChanges:
  stage: merge
  script:
    - wget https://github.com/moparisthebest/static-curl/releases/download/v7.87.0/curl-amd64
    - mv curl-amd64 /usr/local/bin/curl
    - chmod +x /usr/local/bin/curl
    - *curl_template