# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
    desc "Submit a new Beta Build to Crashlytics Beta"
    lane :internal do
        #gradle(task: "clean assembleRelease") #to generate apk
  #       gradle(task: "clean bundleRelease") #to generate aab
      previous_build_number = google_play_track_version_codes(
       # package_name: app_id,
        track: "internal",
       # json_key: json_key_file_path,
      )[0]
      current_build_number = previous_build_number + 1
      increment_version_code(
        gradle_file_path: "./app/build.gradle",
        version_code: current_build_number
      )
        gradle(
        task: 'bundle',
        build_type: 'Release'
        )
        upload_to_play_store(skip_upload_apk: "true", track: 'internal',release_status: 'draft')
    end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
